@echo off
setlocal EnableExtensions
REM Build the docs through run_chimerax.bat so they are generated by THIS
REM worktree/lane's isolated ChimeraX -- i.e. sphinx autodoc imports the bundle
REM version installed in this lane, not the shared one (see run_chimerax.bat).
REM "release" -> stable install; omitted -> the daily build (matching make_win).
set "RELEASE_TOK="
for %%A in (%*) do (
    if /i "%%A"=="release" set "RELEASE_TOK=release"
)

call "%~dp0run_chimerax.bat" %RELEASE_TOK% -m sphinx docs/source src/docs/user

endlocal
