# Clipper plugin to UCSF ChimeraX
# Copyright (C) 2016-2019 Tristan Croll, University of Cambridge

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

# Note that this software makes use of modified versions of the Clipper, LibCCP4
# and MMDB libraries, as well as portions of the Intel Math Kernel Library. Each
# of these is redistributed under its own license terms.

import numpy
from .mapset_base import MapSetBase



class XmapSetBoxParams:
    def __init__(self, origin_xyz=None, origin_grid=None, dim=None):
        self.origin_grid = origin_grid
        self.origin_xyz = origin_xyz
        self.dim = dim


    @property
    def origin_xyz(self):
        return self._origin_xyz

    @origin_xyz.setter
    def origin_xyz(self, origin):
        if origin is None:
            origin = [0,0,0]
        self._origin_xyz = numpy.array(origin, numpy.float32)
        # print("Set XYZ origin to {}".format(self._origin_xyz))

    @property
    def origin_grid(self):
        return self._origin_grid

    @origin_grid.setter
    def origin_grid(self, origin):
        if origin is None:
            origin = [0,0,0]
        self._origin_grid = numpy.array(origin, int)
        # print("Set grid origin to {}".format(self._origin_grid))

    @property
    def dim(self):
        return self._dim

    @dim.setter
    def dim(self, dim):
        if dim is None:
            dim = [1,1,1]
        self._dim = numpy.array(dim, int)
        # print("Set XYZ origin to {}".format(self._dim))


    def __iter__(self):
        return iter((self._origin_xyz, self._origin_grid, self._dim))

    def set(self, params):
        self.origin_xyz=params[0]
        self.origin_grid = params[1]
        self.dim = params[2]


_pad_base = numpy.array([-1,1], int)
class XmapSet(MapSetBase):
    '''
    Handles the organisation, visualisation and re-calculation (where
    applicable) of crystallographic maps. Two general types of maps are
    supported: "static" maps generated from pre-calculated amplitudes and phases
    (e.g. as generated by your favourite refinement package); and "live" maps
    calculated on-the-fly directly from atomic coordinates and experimentally
    observed amplitude data. Each XmapSet handles the data from one crystal.
    Furthermore, live map recalculation requires a single Fobs/sigFobs dataset -
    if more than one is found, the user will be asked to choose.
    '''
    report_timing=False
    #SESSION_SAVE=False

    _default_live_xmap_params = {
        '2mFo-DFc': {'b_sharp': 0, 'is_difference_map': False, 'display': True},
        'mFo-DFc': {'b_sharp': 0, 'is_difference_map': True, 'display': True},
    }
    # Structure-factor component maps for the `clipper debugmaps` command. Each is a
    # live map that FFTs a raw component rather than sigmaa-weighted coefficients:
    # Fcalc = total model (atoms + bulk); Fatoms = atoms only; Fbulk = k_sol*F_mask
    # bulk contribution; Fmask = the (smoothed) solvent-mask transform. They are
    # display-gated (Part B): created hidden and only FFT'd while shown.
    DEBUG_MAP_SPECS = (
        ('Fcalc (total)', 'fcalc'),
        ('Fatoms',        'fatoms'),
        ('Fbulk',         'fbulk'),
        ('Fmask',         'fmask'),
    )
    def __init__(self, manager, crystal_data = None,
        use_live_maps = True,
        use_static_maps = True,
        fsigf_name=None,
        bsharp_vals=None,
        exclude_free_reflections=False,
        fill_with_fcalc=False,
        exclude_missing_reflections=False,
        show_r_factors=True,
        auto_add_to_session=True,
        small_molecule_data=None,
        map_columns=None,
        radiation='xray'):
        '''
        Prepare the XmapSet and create all required maps.

        Args:
            * manager:
                - the master `MapMgr` object
            * crystal_data:
                - a ReflectionDataContainer object holding all the data for a
                  single crystal
            * use_live_maps:
                - if True, then the F/sigF data in crystal_data (if present)
                  will be used to generate maps that automatically update on
                  changes to the atomic model
            * use_static_maps:
                - if True, each F/phi dataset found in crystal_data will be
                  used to generate a static (unchanging) crystallographic map.
            * fsigf_name:
                - If the dataset has multiple F/sigF columns, setting this
                  value will explicitly choose the one to use. Otherwise, a
                  dialog will be launched allowing interactive selection.
            * bsharp_vals:
                - (only applicable when use_live_maps is True) a list of values
                  for sharpening/smoothing B-factors. For each value in the
                  list, a new map will be created from amplitudes scaled by the
                  B-factor value. Negative values lead to smoothing, positive
                  values to sharpening. If None, a B-factor will be chosen for
                  optimum viewing.
            * exclude_free_reflections
                - (only applicable when use_live_maps is True) if True, live
                  maps will use all measured reflections in their calculations.
                  NOTE: if the maps are to be used for fitting purposes, it is
                  strongly advised to set this argument to False.
            * fill_with_fcalc
                - (only applicable when use_live_maps is True) if True, missing
                  reflections will be approximated from the model for map
                  calculations. Note that this will lead to some level of model
                  bias (potentially serious of a large fraction of reflections
                  are missing).
            * exclude_missing_reflections
                - (only applicable when both use_live_maps,
                  exclude_free_reflections and fill_with_fcalc are true)
                  if True, only reflections that are excluded due to being part
                  of the free set will be replaced with Fcalc.
            * show_r_factors
                - (only applicable when use_live_maps is True) if True, R-work
                  and R-free will be reported to the status bar every time maps
                  are recalculated
        '''
        import os
        if crystal_data is not None:
            data_name = self.data_name = os.path.basename(crystal_data.filename)
        else:
            data_name = ''
        super().__init__(manager, data_name)
        self.triggers.add_trigger('live recalc changed')

        session = self.session


        trigger_names = (
            'maps recalculated',
        )
        for t in trigger_names:
            self.triggers.add_trigger(t)
        self._show_r_factors = show_r_factors

        xm = self._live_xmap_mgr = None
        self._small_molecule_data = small_molecule_data
        # X-ray (default) vs electron scattering factors for the live Fcalc. For
        # small-molecule maps radiation travels inside small_molecule_data; for the
        # macromolecular path it is applied to the C++ Xtal_thread_mgr (see
        # _launch_live_xmap_mgr).
        self._radiation = radiation
        self._live_update = False
        self._recalc_needed = False
        self._model_changes_handler = None
        self._model_swap_handler = None
        self._delayed_recalc_handler = None

        self._box_params = XmapSetBoxParams()
        self._maps_initialized=False
        self._f_sigf_data_name = None

        # Small-molecule live maps supply their crystal definition + Fobs + atom
        # scaffold directly (see maps.small_molecule_map), bypassing the MTZ /
        # ReflectionDataContainer / bulk-solvent path entirely.
        if small_molecule_data is not None:
            self._init_small_molecule_maps()
        elif crystal_data is not None:
            self.add([crystal_data])
            self.init_maps(use_static_maps, use_live_maps,
            fsigf_name, bsharp_vals, exclude_free_reflections,
            fill_with_fcalc, exclude_missing_reflections,
            map_columns=map_columns)
        if auto_add_to_session:
            manager.add([self])

    @MapSetBase.name.getter
    def name(self):
        return f'Crystallographic maps({self._name})'
    
    @property
    def base_name(self):
        return self._name

    def _launch_small_molecule_xmap_mgr(self, smd):
        '''Build the unit-cell/box scaffold and the SmallMoleculeXmapMgr for a
        small-molecule crystal, WITHOUT adding any maps. Shared by
        _init_small_molecule_maps (fresh open, which then adds the 2Fo-Fc / Fo-Fc maps)
        and _end_restore_session_cb (session restore, where the maps are themselves
        restored as child models and only re-registered with the manager).'''
        self._small_molecule_data = smd
        from .. import Unit_Cell, atom_list_from_sel
        alist = atom_list_from_sel(self.structure.atoms)
        self._unit_cell = Unit_Cell(alist, smd['cell'], smd['spacegroup'], smd['grid'], 5)
        if self.spotlight_mode:
            self._box_changed_cb('init', (self.spotlight_center, self.display_radius))
        else:
            self.expand_to_cover_coords(self.master_map_mgr.last_covered_selection, 10)
        from .small_molecule_map import SmallMoleculeXmapMgr
        self._live_xmap_mgr = SmallMoleculeXmapMgr(
            smd['hklinfo'], smd['cell'], smd['spacegroup'], smd['grid'],
            smd['fobs'], smd['structure'],
            radiation=smd.get('radiation', 'xray'))
        self._maps_initialized = True

    def _init_small_molecule_maps(self):
        '''Set up live small-molecule maps from self._small_molecule_data (cell,
        spacegroup, grid, hklinfo, resolution, fobs amplitudes and the live structure).
        Uses SmallMoleculeXmapMgr (FFT structure factors, no bulk solvent) in place of
        the C++ Xtal_thread_mgr, and reuses the standard box/spotlight + live-recalc
        machinery. The manager reads per-atom SF inputs live from the structure.'''
        self._launch_small_molecule_xmap_mgr(self._small_molecule_data)
        # Plain 2Fo-Fc / Fo-Fc, NOT the macromolecular 2mFo-DFc / mFo-DFc: these
        # coefficients carry Fcalc phases with no sigma-A figure-of-merit (m) or
        # weighting (D) and no R-free set (see SmallMoleculeXmapMgr).
        self.add_live_xmap('2Fo-Fc', is_difference_map=False)
        diff = self.add_live_xmap('Fo-Fc', is_difference_map=True)
        # Small-molecule difference maps are contoured at a fixed ABSOLUTE level
        # (electrons/A^3), not sigma. The map is on the e/A^3 scale (see
        # SmallMoleculeXmapMgr), and a well-fit model leaves a near-flat residual
        # whose sigma is tiny - so the macromolecular +/-3 sigma default sits in the
        # noise (blobs over every atom). +/-0.3 e/A^3 is the usual small-molecule level.
        self._set_absolute_difference_contour(diff, level=0.3)
        self.live_update = True

    def _set_absolute_difference_contour(self, handler, level=0.3):
        # Replace the sigma-relative levels with absolute ones (same signs, so the
        # positive/negative colours stay correct) and pin them: clearing
        # _contour_sigma stops XmapHandler_Live._map_recalc_cb from rescaling the
        # levels by the sigma ratio on each recalculation.
        #
        # `level` is a FLOOR, not a fixed value: a well-fit light-atom structure
        # leaves a near-flat residual whose sigma is tiny, so a +/-3 sigma default
        # would sit in the noise (blobs over every atom) - hence the 0.3 e/A^3 floor.
        # But a heavy-atom / atomic-resolution structure has genuinely larger
        # residuals (hard-to-model heavy atoms plus bonding density), where 0.3 is
        # far below the noise floor and the map fills with a mess (COD 2020656). Use
        # max(floor, 3 * robust sigma): the floor wins for clean light-atom maps, the
        # robust 3-sigma wins for busy ones. Robust (MAD) sigma, so a couple of large
        # heavy-atom difference lobes don't themselves inflate the level.
        import numpy
        robust = getattr(handler, 'robust_sigma', None)
        if robust:
            level = max(level, 3.0 * robust)
        signs = [s.level for s in handler.surfaces] if handler.surfaces else [level, -level]
        handler.set_parameters(
            surface_levels=[numpy.sign(c) * level if c else level for c in signs])
        handler._contour_sigma = None

    def init_maps(self, use_static_maps=True, use_live_maps=True,
            fsigf_name=None, bsharp_vals=None, exclude_free_reflections=False,
            fill_with_fcalc=False, exclude_missing_reflections=False,
            map_columns=None):
        if self._maps_initialized:
            raise RuntimeError('Maps have already been initialised!')
        from .. import (
            HKL_data_F_sigF, HKL_data_F_sigF_ano,
            HKL_data_I_sigI, HKL_data_I_sigI_ano
        )
        self._known_experimental_datatypes = (
            HKL_data_F_sigF, HKL_data_F_sigF_ano,
            HKL_data_I_sigI, HKL_data_I_sigI_ano
        )
        session = self.session

        crystal_data = self.crystal_data

        # Since the Unit_Cell class does much of its work in grid coordinates,
        # each XmapSet object needs its own Unit_Cell instance (since there is
        # no guarantee that resolutions will be equal).
        from .. import Unit_Cell, atom_list_from_sel
        alist = atom_list_from_sel(self.structure.atoms)
        self._unit_cell = Unit_Cell(alist, self.cell, self.spacegroup,
            self.grid, 5)
        # Work out if we have experimental data, and launch the live data
        # manager if so.
        if self.spotlight_mode:
            self._box_changed_cb('init', (self.spotlight_center, self.display_radius))
        else:
            self.expand_to_cover_coords(self.master_map_mgr.last_covered_selection, 10)

        if use_live_maps:
            if fsigf_name is not None:
                fsigf = crystal_data.experimental_data.datasets.get(fsigf_name, None)
                if fsigf is None:
                    session.logger.info('WARNING: no experimental reflection data found with the '
                        'given label {}! Launching chooser dialog...'.format(fsigf_name))
                    fsigf_name = None

            if fsigf_name is None:
                choice = self._choose_reflection_data(crystal_data)
                if choice is not None:
                    fsigf_name, fsigf = choice
                else:
                    fsigf_name = fsigf = None

            if fsigf is not None:
                if fsigf.dtype in (HKL_data_I_sigI, HKL_data_I_sigI_ano):
                    session.logger.info('Reflection data provided as intensities. '
                        'Performing French & Wilson scaling to convert to amplitudes...')
                    from chimerax.clipper.reflection_tools import french_wilson_analytical
                    fsigf_data = french_wilson_analytical(fsigf.data)
                    from ..clipper_mtz import ReflectionDataExp
                    fsigf = ReflectionDataExp('French and Wilson Amplitudes', self.session, fsigf_data)
                    crystal_data.experimental_data.add([fsigf])
                else:
                    fsigf_data = fsigf.data
                self._f_sigf_data_name = fsigf.name
                self._launch_live_xmap_mgr(crystal_data, fsigf_data)
                if bsharp_vals is None:
                    bsharp_vals = [viewing_recommended_bsharp(self.resolution)]
                if bsharp_vals:
                    if max(bsharp_vals) > 0:
                        map_style = 'mesh'
                        transparency = 0.0
                        contour=self.STANDARD_LOW_CONTOUR
                    else:
                        map_style='surface'
                        transparency=0.6
                        contour=self.STANDARD_HIGH_CONTOUR
                map_params = self._default_live_xmap_params.copy()
                map_params['2mFo-DFc']['style'] = map_style
                map_params['2mFo-DFc']['transparency'] = transparency
                map_params['2mFo-DFc']['contour'] = contour

                self._prepare_standard_live_maps(exclude_free_reflections,
                    fill_with_fcalc, exclude_missing_reflections,
                    map_params)
                from math import sqrt
                for b in bsharp_vals:
                    style = 'mesh'
                    transparency = 0.0
                    if b<0:
                        name_str = "2mFo-DFc_smooth_{:.0f}".format(-b)
                        contour = self.STANDARD_LOW_CONTOUR
                    else:
                        name_str = "2mFo-DFc_sharp_{:.0f}".format(b)
                        if b == max(bsharp_vals):
                            style = 'surface'
                            transparency = 0.6
                            contour = self.STANDARD_HIGH_CONTOUR
                    self.add_live_xmap(name_str,
                        b_sharp=b,
                        is_difference_map=False,
                        exclude_free_reflections=exclude_free_reflections,
                        fill_with_fcalc=fill_with_fcalc,
                        exclude_missing_reflections=exclude_missing_reflections,
                        style=style,
                        transparency=transparency,
                        contour=contour,
                        # These heuristic sharpened/smoothed maps are the ones a
                        # bare "clipper bsharp <value>" should retune; the raw
                        # 2mFo-DFc reference map (added above) stays put.
                        bsharp_designated=True
                        )
        if self.live_xmap_mgr is not None:
            self.live_update=True
        if use_static_maps:
            cdata = crystal_data.calculated_data
            selected = _select_calc_datasets(list(cdata), map_columns)
            for dataset in cdata:
                if dataset not in selected:
                    continue
                xmap = self.add_static_xmap(dataset)
                # When no explicit selection was given, preserve the historical
                # behaviour: open every map but hide probable Fcalc maps. When the
                # caller (command keyword or MTZ browser) named the maps to open,
                # honour that exactly and display them all.
                if map_columns is None and xmap.is_probably_fcalc_map():
                    xmap.display = False
        self._maps_initialized=True

    @property
    def path(self):
        if self.crystal_data is not None:
            return self.crystal_data.path
        if self._small_molecule_data is not None:
            return self._small_molecule_data.get('path')
        return None

    @property
    def box_params(self):
        return self._box_params

    @property
    def live_xmap_mgr(self):
        return self._live_xmap_mgr

    @property
    def occupancy_weighted_solvent_mask(self):
        '''
        If True (default), the bulk-solvent mask is occupancy-weighted: a
        partial-occupancy atom (e.g. a partially-occupied ligand or one altloc of
        a branched side chain) excludes solvent only fractionally, rather than
        stamping a full exclusion sphere. Set False for the original binary mask
        (useful for A/B comparison against other refinement packages).
        '''
        xm = self._live_xmap_mgr
        if xm is not None:
            return xm.occupancy_weighted_solvent_mask
        return getattr(self, '_occupancy_weighted_solvent_mask', True)

    @occupancy_weighted_solvent_mask.setter
    def occupancy_weighted_solvent_mask(self, flag):
        flag = bool(flag)
        self._occupancy_weighted_solvent_mask = flag
        xm = self._live_xmap_mgr
        if xm is not None and xm.occupancy_weighted_solvent_mask != flag:
            xm.occupancy_weighted_solvent_mask = flag
            # Changing the mode alters the mask (and hence f_bulk), so refit the
            # bulk solvent and recompute the maps.
            xm.bulk_solvent_optimization_needed()
            self.recalc_needed()

    @property
    def all_reflections(self):
        '''
        If False (default), the Fcalc->Fobs bulk-solvent scale is fit on a fixed,
        seeded subset of reflections (see scaling_seed): fast and reproducible, with
        a tiny fixed bias vs the full fit. If True, it is fit over all reflections -
        exact and unbiased, at a larger (one-off) cost. Leave False for interactive
        live maps; True is used internally where the exact scale matters (e.g. the
        B-factor/occupancy refiner).
        '''
        xm = self._live_xmap_mgr
        if xm is not None:
            return xm.all_reflections
        return getattr(self, '_all_reflections', False)

    @all_reflections.setter
    def all_reflections(self, flag):
        flag = bool(flag)
        self._all_reflections = flag
        xm = self._live_xmap_mgr
        if xm is not None and xm.all_reflections != flag:
            xm.all_reflections = flag
            xm.bulk_solvent_optimization_needed()
            self.recalc_needed()

    @property
    def scaling_reflections_per_bin(self):
        '''Reflections per resolution bin in the seeded subset used to fit the
        bulk-solvent scale (default 500). Ignored when all_reflections is True.
        Exposed for tuning/characterising the subset size.'''
        xm = self._live_xmap_mgr
        if xm is not None:
            return xm.scaling_reflections_per_bin
        return getattr(self, '_scaling_reflections_per_bin', 500)

    @scaling_reflections_per_bin.setter
    def scaling_reflections_per_bin(self, n):
        n = int(n)
        self._scaling_reflections_per_bin = n
        xm = self._live_xmap_mgr
        if xm is not None and xm.scaling_reflections_per_bin != n:
            xm.scaling_reflections_per_bin = n
            xm.bulk_solvent_optimization_needed()
            self.recalc_needed()

    @property
    def scaling_num_bins(self):
        '''Number of resolution bins in the seeded subset used to fit the
        bulk-solvent scale (default 20). Ignored when all_reflections is True.'''
        xm = self._live_xmap_mgr
        if xm is not None:
            return xm.scaling_num_bins
        return getattr(self, '_scaling_num_bins', 20)

    @scaling_num_bins.setter
    def scaling_num_bins(self, n):
        n = int(n)
        self._scaling_num_bins = n
        xm = self._live_xmap_mgr
        if xm is not None and xm.scaling_num_bins != n:
            xm.scaling_num_bins = n
            xm.bulk_solvent_optimization_needed()
            self.recalc_needed()

    @property
    def scaling_seed(self):
        '''Seed for the fixed reflection subset used to fit the bulk-solvent scale
        (default 10061865). The subset is drawn once and reused across recalculations,
        so the scale is reproducible; vary the seed to probe sensitivity to which
        reflections were chosen. Ignored when all_reflections is True.'''
        xm = self._live_xmap_mgr
        if xm is not None:
            return xm.scaling_seed
        return getattr(self, '_scaling_seed', 10061865)

    @scaling_seed.setter
    def scaling_seed(self, s):
        s = int(s)
        self._scaling_seed = s
        xm = self._live_xmap_mgr
        if xm is not None and xm.scaling_seed != s:
            xm.scaling_seed = s
            xm.bulk_solvent_optimization_needed()
            self.recalc_needed()

    @property
    def live_xmaps(self):
        return [m for m in self.child_models() if isinstance(m, XmapHandler_Live)]

    @property
    def static_xmaps(self):
        return [m for m in self.child_models() if isinstance(m, XmapHandler_Static)]

    @property
    def crystal_data(self):
        from ..clipper_mtz import ReflectionDataContainer
        for m in self.child_models():
            if type(m) == ReflectionDataContainer:
                return m
        return None

    @property
    def free_flags(self):
        cdata = self.crystal_data
        if cdata is None:
            return None
        return cdata.free_flags

    @property
    def show_r_factors(self):
        return self._show_r_factors

    @show_r_factors.setter
    def show_r_factors(self, flag):
        self._show_r_factors = flag

    @property
    def live_update(self):
        return self._live_update

    @live_update.setter
    def live_update(self, flag):
        if flag == self._live_update:
            return
        if flag:
            if self.live_xmap_mgr is None:
                self.session.logger.warning('Map set {} has no experimental '
                    'data! Live map recalculation is not possible.'.format(self.name))
            else:
                if self._model_changes_handler is None:
                    self._model_changes_handler = self.crystal_mgr.triggers.add_handler(
                        'atoms changed', self._model_changed_cb
                    )
                if self._model_swap_handler is None:
                    self._model_swap_handler = self.crystal_mgr.triggers.add_handler(
                        'model replaced', self._model_changed_cb
                    )
        else:
            mch = self._model_changes_handler
            msh = self._model_swap_handler
            for h in (mch, msh):
                if h is not None:
                    self.crystal_mgr.triggers.remove_handler(h)

            self._model_changes_handler = None
            self._model_swap_handler = None
        self.triggers.activate_trigger('live recalc changed', flag)
        self._live_update = flag

    @property
    def rfree(self):
        if self.live_xmap_mgr is None:
            return None
        return self.live_xmap_mgr.rfree

    @property
    def rwork(self):
        if self.live_xmap_mgr is None:
            return None
        return self.live_xmap_mgr.rwork

    @property
    def experimental_data(self):
        if self.crystal_data is not None:
            return self.crystal_data.experimental_data.datasets
        return {}

    @property
    def hklinfo(self):
        if self.crystal_data is not None:
            return self.crystal_data.hklinfo
        if self._small_molecule_data is not None:
            return self._small_molecule_data['hklinfo']
        return None

    @property
    def cell(self):
        if self.crystal_data is not None:
            return self.crystal_data.cell
        if self._small_molecule_data is not None:
            return self._small_molecule_data['cell']
        return None

    @property
    def spacegroup(self):
        if self.crystal_data is not None:
            return self.crystal_data.spacegroup
        if self._small_molecule_data is not None:
            return self._small_molecule_data['spacegroup']
        return None

    @property
    def resolution(self):
        if self.crystal_data is not None:
            return self.crystal_data.resolution.limit
        if self._small_molecule_data is not None:
            return self._small_molecule_data['resolution']
        return None

    @property
    def grid(self):
        if self.crystal_data is not None:
            return self.crystal_data.grid_sampling
        if self._small_molecule_data is not None:
            return self._small_molecule_data['grid']
        return None

    @property
    def unit_cell(self):
        return self._unit_cell

    def _launch_live_xmap_mgr(self, crystal_data, f_sigf):
        from time import time
        start_time = time()
        from ..util import available_cores
        # The master C++ manager for handling all map operations
        from ..clipper_python.ext import Xtal_thread_mgr
        xm = self._live_xmap_mgr = Xtal_thread_mgr(self.hklinfo,
            crystal_data.free_flags.data, self.grid, f_sigf,
            num_threads=available_cores())
        # Select the scattering-factor table before the first (threaded) recalc.
        # Electron factors give an electrostatic-potential map + kinematical R-factor
        # for micro-ED / 3D-ED; X-ray (default) is byte-identical to before.
        radiation = getattr(self, '_radiation', 'xray')
        from ..clipper_python import AtomShapeFn
        xm.radiation = (AtomShapeFn.ELECTRON if str(radiation).lower() == 'electron'
                        else AtomShapeFn.XRAY)
        # Occupancy-weighted bulk-solvent mask (default on). Apply any preference
        # set before the manager existed; harmless no-op when left at the default.
        xm.occupancy_weighted_solvent_mask = getattr(
            self, '_occupancy_weighted_solvent_mask', True)
        # Seeded-subset scaling knobs (size + seed) and the all-reflections toggle.
        # Apply only preferences set before the manager existed; the default (seeded
        # subset with the C++ default seed) needs no push. Enabling all_reflections
        # re-derives the working set, so avoid a needless startup re-sample when left
        # at the default.
        if getattr(self, '_scaling_reflections_per_bin', None) is not None:
            xm.scaling_reflections_per_bin = self._scaling_reflections_per_bin
        if getattr(self, '_scaling_num_bins', None) is not None:
            xm.scaling_num_bins = self._scaling_num_bins
        if getattr(self, '_scaling_seed', None) is not None:
            xm.scaling_seed = self._scaling_seed
        if getattr(self, '_all_reflections', False):
            xm.all_reflections = True
        # from ..util import atom_list_from_sel
        # ca = self._clipper_atoms = atom_list_from_sel(self.structure.atoms)
        atoms = self.structure.atoms
        from ..scattering import ionic_scattering_names
        xm.init(atoms.pointers, ionic_scattering_names(atoms, radiation=radiation))
        end_time = time()
        print(f'Launching live xmap mgr took {end_time-start_time} seconds.')

    def _prepare_standard_live_maps(self, exclude_free_reflections,
        fill_with_fcalc, exclude_missing_reflections, map_params):
        xm = self.live_xmap_mgr
        if xm is None:
            return
        for name, params in map_params.items():
            self.add_live_xmap(name, **params,
                exclude_free_reflections=exclude_free_reflections,
                fill_with_fcalc=fill_with_fcalc,
                exclude_missing_reflections=exclude_missing_reflections
                )


    def set_xmap_display_style(self, xmap_handler, is_difference_map=False,
        color=None, style=None, transparency=None, contour=None):
        if style is None:
            style = 'mesh'
        if is_difference_map and color is not None and len(color) != 2:
            err_string = '''
            ERROR: For a difference map you need to define colours for
            both positive and negative contours, as:
            [[r,g,b,a],[r,g,b,a]] in order [positive, negative].
            '''
            raise TypeError(err_string)
        if color is None:
            if is_difference_map:
                color = self.DEFAULT_DIFF_MAP_COLORS
            elif style == 'mesh':
                color = [self.DEFAULT_MESH_MAP_COLOR]
            else:
                color = [self.DEFAULT_SOLID_MAP_COLOR]
        if transparency is not None:
            for c in color:
                c[-1] = 1-transparency
        if contour is None:
            if is_difference_map:
                contour = self.STANDARD_DIFFERENCE_MAP_CONTOURS
            else:
                contour = self.STANDARD_HIGH_CONTOUR


        # For small-molecule maps this is a winsorized sigma (robust to heavy-atom
        # peaks); for macromolecular/static maps it is just the raw sigma.
        sigma_basis = getattr(xmap_handler, 'contour_sigma_basis', xmap_handler.sigma)
        levels = numpy.array(contour) * sigma_basis

        xmap_handler.set_parameters(**{'cap_faces': False,
                                  'surface_levels': levels,
                                  'show_outline_box': False,
                                  'surface_colors': color,
                                  'square_mesh': False,
                                  # 'transparency_factor': transparency,
                                  'flip_normals': True,
                                  })
        xmap_handler.set_display_style(style)
        # Record the sigma value these (absolute) levels were set against, so the
        # contours can be kept fixed in sigma units if the map is later rescaled
        # (see XmapHandler_Live._map_recalc_cb).
        xmap_handler._contour_sigma = sigma_basis

    def add_live_xmap(self, name,
        b_sharp=0,
        is_difference_map=False,
        exclude_missing_reflections=False,
        exclude_free_reflections=True,
        fill_with_fcalc=True,
        color=None,
        style=None,
        transparency=0.0,
        contour=None,
        display=True,
        auto_add_to_session=True,
        bsharp_adjustable=None,
        bsharp_designated=False):
        '''
        Add a "live" crystallographic map, calculated from atomic positions and
        experimental x-ray reflection data. The map will be automatically
        recalculated in the background whenever changes are made to the atomic
        model.

        bsharp_adjustable:
            Whether "clipper bsharp" may change this map's sharpening B-factor.
            If None (default), resolves to True for normal maps and False for
            difference maps. Pass False to lock a map (e.g. ISOLDE's hidden MDFF
            fitting map, which must keep its construction B-factor).
        bsharp_designated:
            Whether this map is the default target of "clipper bsharp" applied at
            model/whole-dataset scope. Set True for the heuristic sharpened/
            smoothed viewing map; leave False for the raw reference map.
        '''
        if bsharp_adjustable is None:
            bsharp_adjustable = not is_difference_map
        rebuild_args = {
            'b_sharp':                      b_sharp,
            'is_difference_map':            is_difference_map,
            'exclude_missing_reflections':  exclude_missing_reflections,
            'exclude_free_reflections':     exclude_free_reflections,
            'fill_with_fcalc':              fill_with_fcalc,
        }

        xm = self._live_xmap_mgr
        if xm is None:
            raise RuntimeError('This crystal dataset has no experimental amplitudes!')
        xm.add_xmap(name, b_sharp, is_difference_map=is_difference_map,
            exclude_missing_reflections=exclude_missing_reflections,
            exclude_free_reflections=exclude_free_reflections,
            fill_with_fcalc = fill_with_fcalc)
        new_handler = XmapHandler_Live(self, name,
            is_difference_map=is_difference_map)
        # Difference maps are never adjustable regardless of the argument.
        new_handler.bsharp_adjustable = bsharp_adjustable and not is_difference_map
        new_handler.bsharp_designated = bsharp_designated and new_handler.bsharp_adjustable
        self.set_xmap_display_style(new_handler,
            is_difference_map=is_difference_map,
            color=color,
            style=style,
            transparency=transparency,
            contour=contour)
        new_handler._rebuild_args = rebuild_args
        if auto_add_to_session:
            self.add([new_handler])
            if display:
                new_handler.show()
                self.master_map_mgr.rezone_needed()
            else:
                new_handler.display=False
        return new_handler

    def add_live_debug_xmap(self, name, component, color=None, style=None,
        transparency=0.0, contour=None):
        '''
        Add a display-gated live map for a raw structure-factor component (one of
        'fcalc', 'fatoms', 'fbulk', 'fmask'). The map is created hidden; while
        hidden it is skipped by the background recalculation (no FFT), and it is
        brought up to date only when shown or otherwise read. Not saved in sessions.
        '''
        xm = self._live_xmap_mgr
        if xm is None:
            raise RuntimeError('This crystal dataset has no experimental amplitudes!')
        xm.add_debug_xmap(name, component)
        new_handler = XmapHandler_Live(self, name, is_difference_map=False)
        new_handler._display_gated = True
        new_handler.bsharp_adjustable = False
        # Debug maps are a transient diagnostic aid: keep them out of saved sessions
        # (the restore path replays add_xmap(**_rebuild_args), which does not apply
        # to component maps).
        new_handler.SESSION_SAVE = False
        self.set_xmap_display_style(new_handler, is_difference_map=False,
            color=color, style=style, transparency=transparency, contour=contour)
        self.add([new_handler])
        # Created hidden; sync the manager's display state so it starts gated-off.
        new_handler.display = False
        xm.set_map_displayed(name, False)
        return new_handler

    def add_debug_maps(self):
        '''Create the standard set of live structure-factor component maps.'''
        xm = self._live_xmap_mgr
        if xm is None:
            from chimerax.core.errors import UserError
            raise UserError('This crystal dataset has no live maps to debug '
                '(no experimental amplitudes).')
        if getattr(self, '_debug_handlers', None):
            return self._debug_handlers
        self._register_debug_display_handler()
        handlers = []
        for name, component in self.DEBUG_MAP_SPECS:
            handlers.append(self.add_live_debug_xmap(name, component))
        self._debug_handlers = handlers
        return handlers

    def remove_debug_maps(self):
        '''Remove any live structure-factor component maps.'''
        handlers = getattr(self, '_debug_handlers', None)
        if not handlers:
            return
        xm = self._live_xmap_mgr
        for h in handlers:
            name = h._map_name
            if not h.deleted:
                h.delete()
            if xm is not None:
                try:
                    xm.delete_xmap(name)
                except Exception:
                    pass
        self._debug_handlers = []
        self._deregister_debug_display_handler()

    def _register_debug_display_handler(self):
        if getattr(self, '_debug_display_handler', None) is not None:
            return
        from chimerax.core.models import MODEL_DISPLAY_CHANGED
        self._debug_display_handler = self.session.triggers.add_handler(
            MODEL_DISPLAY_CHANGED, self._debug_map_display_changed_cb)

    def _deregister_debug_display_handler(self):
        h = getattr(self, '_debug_display_handler', None)
        if h is not None:
            self.session.triggers.remove_handler(h)
            self._debug_display_handler = None

    def _debug_map_display_changed_cb(self, trigger_name, model):
        # A gated component map's visibility drives whether it is FFT'd. On show,
        # mark it live and refill from fresh data (the read triggers ensure_current
        # in the C++ manager); on hide, mark it gated-off.
        if not isinstance(model, XmapHandler_Live):
            return
        if not getattr(model, '_display_gated', False) or model.mapset is not self:
            return
        xm = self._live_xmap_mgr
        if xm is None:
            return
        shown = bool(model.display)
        xm.set_map_displayed(model._map_name, shown)
        if shown:
            model._map_recalc_cb(model._map_name)

    def add_static_xmap(self, dataset,
        is_difference_map=None,
        color=None,
        style=None,
        contour=None,
        display=True,
        auto_add_to_session=True,
        _session_restore=False):
        '''
        Add a crystallographic map based on pre-calculated amplitudes and
        phases. This map will remain unchanged no matter what happens to the
        atomic model.
        '''
        data = dataset.data
        from .. import HKL_data_F_phi
        if not isinstance(data, HKL_data_F_phi):
            raise RuntimeError('Invalid data type: {}!'.format(type(data)))
        if is_difference_map is None:
            is_difference_map = dataset.is_difference_map
        new_handler = XmapHandler_Static(self, dataset,
            is_difference_map = is_difference_map)
        if not _session_restore:
            self.set_xmap_display_style(new_handler,
                is_difference_map=is_difference_map,
                color=color,
                style=style,
                contour=contour
                )
        if auto_add_to_session:
            self.add([new_handler])
            if display:
                new_handler.show()
                self.master_map_mgr.rezone_needed()
            else:
                new_handler.display=False
        return new_handler

    def save_mtz(self, filename, save_input_data=True, save_output_fobs=True,
            save_map_coeffs=False):
        from chimerax.clipper.io import mtz_write
        data = {}
        if save_output_fobs or save_map_coeffs:
            data['out'] = {}
        if save_input_data:
            data['in'] = {dname: d.data for dname, d in self.experimental_data.items()}
        if save_output_fobs:
            data['out']['[FOBS, SIGFOBS]'] = self.live_xmap_mgr.f_obs
        if save_map_coeffs:
            out = data['out']
            out['[FCALC, PHFCALC]'] = self.live_xmap_mgr.f_calc
            out['[2FOFC, PH2FOFC]'] = self.live_xmap_mgr.base_2fofc
            out['[FOFC, PHFOFC]'] = self.live_xmap_mgr.base_fofc
        mtz_write.write_mtz(filename, self.hklinfo, self.free_flags.data, data)

    def _choose_reflection_data(self, crystal_data):
        from .. import HKL_data_F_sigF
        exp_data = crystal_data.experimental_data
        reflections = {key: data for key, data in exp_data.datasets.items() if data.dtype in self._known_experimental_datatypes}
        # fsigfs = {key: data for key, data in exp_data.datasets.items() if data.dtype==HKL_data_F_sigF}
        if not len(reflections):
            return None
        elif len(reflections) == 1:
            ret = list(reflections.items())[0]
            return ret
        else:
            choice = self._reflection_data_chooser(list(reflections.keys()))
            if choice is None:
                return None
            return (choice, reflections[choice])

    def _reflection_data_chooser(self, possible_names,
        title = 'Choose the dataset to use for map calculations'):
        from Qt.QtWidgets import QInputDialog
        choice, ok_pressed = QInputDialog.getItem(self.session.ui.main_window,
            title, 'Label: ', possible_names, 0, False)
        if ok_pressed and choice:
            return choice
        return None

    def expand_to_cover_coords(self, coords, padding):
        cell = self.cell
        grid = self.grid
        pad = _calculate_grid_padding(padding, grid, cell)
        from ..clipper_util import get_minmax_grid
        box_bounds_grid = \
            get_minmax_grid(coords, cell, grid)
        box_bounds_grid[0] -= pad
        box_bounds_grid[1] += pad
        self.set_box_limits(box_bounds_grid, force_fill=True)

    def set_box_limits(self, minmax, force_fill = False):
        '''
        Set the map box to fill a volume encompassed by the provided minimum
        and maximum grid coordinates. Automatically turns off live scrolling.
        '''
        self.live_scrolling = False
        from .. import Coord_grid
        cmin = Coord_grid(minmax[0])
        cmin_xyz = cmin.coord_frac(self.grid).coord_orth(self.cell).xyz
        dim = (minmax[1]-minmax[0])
        self.box_params.set((cmin_xyz, minmax[0], dim))
        self.triggers.activate_trigger('map box changed', None)

    # Callbacks

    _map_impacting_changes = set ((
        "aniso_u changed",
        "bfactor changed",
        "coord changed",
        "coordset changed",
        "occupancy changed",
    ))
    _bulk_solvent_recalc_changes = set ((
        "aniso_u changed",
        "bfactor changed",
        "coordset changed",
        "occupancy changed",
    ))
    def _model_changed_cb(self, trigger_name, changes):
        recalc_needed = False
        if trigger_name == 'model replaced':
            recalc_needed = True
        elif changes is not None:
            changes = changes[1]
            atom_changes = set(changes.atom_reasons()).intersection(self._map_impacting_changes)
            added = len(changes.created_atoms())
            deleted = changes.num_deleted_atoms()
            recalc_needed = (atom_changes or added or deleted)
            if added or len(self._bulk_solvent_recalc_changes.intersection(atom_changes)):
                self.live_xmap_mgr.bulk_solvent_optimization_needed()

        if recalc_needed:
            self.recalc_needed()

    def recalc_needed(self):
        self._recalc_needed = True
        if self._delayed_recalc_handler is None:
            self._delayed_recalc_handler = self.session.triggers.add_handler(
                'new frame', self._recalculate_maps_if_needed
            )


    def _recalculate_maps_if_needed(self, *_):
        if self.deleted or self.structure.deleted:
            if self._delayed_recalc_handler is not None:
                self._delayed_recalc_handler.remove()
                self._delayed_recalc_handler = None
            return
        xm = self.live_xmap_mgr
        if xm is None:
            return
        if self._recalc_needed and not xm.thread_running:
            self.recalculate_all_maps(self.structure.atoms)
            if self._delayed_recalc_handler is not None:
                self.session.triggers.remove_handler(self._delayed_recalc_handler)
                self._delayed_recalc_handler = None

    def recalculate_all_maps(self, atoms):
        if self.report_timing:
            from time import perf_counter
            start_time = perf_counter()
        if len(self.live_xmaps) == 0:
            self._recalc_needed = False
            return
        import ctypes
        # from .. import atom_list_from_sel
        from ..delayed_reaction import delayed_reaction
        from ..scattering import ionic_scattering_names
        xm = self.live_xmap_mgr
        # ca = self._clipper_atoms = atom_list_from_sel(atoms)
        # Ionic scattering factors for any monatomic ions; recomputed here (rather
        # than cached) so it tracks ions added/removed during modelling. The
        # per-atom species aligns by index with atoms.pointers. Uses the same
        # radiation as the manager so per-frame recalcs stay on the electron table
        # for micro-ED (otherwise they would silently revert to X-ray).
        elements = ionic_scattering_names(atoms, radiation=getattr(self, '_radiation', 'xray'))
        # Keep gated component maps' display state current so this recalc FFTs only
        # the ones currently shown (Part B); hidden ones are refreshed lazily on read.
        for h in getattr(self, '_debug_handlers', None) or ():
            if not h.deleted:
                xm.set_map_displayed(h._map_name, bool(h.display))
        delayed_reaction(self.session.triggers, 'new frame',
            xm.recalculate_all_maps, [atoms.pointers, elements],
            xm.ready,
            self._apply_new_maps, []
            )
        if self.report_timing:
            def set_fft_start_time(*_):
                from time import perf_counter
                self._recalc_start_time = perf_counter()
                from chimerax.core.triggerset import DEREGISTER
                return DEREGISTER
            self.session.triggers.add_handler('new frame', set_fft_start_time)
            
        self._recalc_needed = False
        if self.report_timing:
            self.session.logger.info(f'Starting map recalculation for live xmapset #{self.id_string} took {(perf_counter()-start_time)*1e3:.3f} ms.')

    def _apply_new_maps(self):
        if self.deleted:
            return
        if self.report_timing:
            from time import perf_counter
            start_time = perf_counter()
            print(f'FFT took {(start_time - self._recalc_start_time)*1000:.1f} ms.')
        xm = self.live_xmap_mgr
        xm.apply_new_maps()
        if self.show_r_factors:
            self.session.logger.status(self._r_factor_string(precision=4),
                                       secondary=True)
        if self.report_timing:
            self.session.logger.info(f'Applying new maps for live xmapset #{self.id_string} before "maps recalculated" trigger took {(perf_counter()-start_time)*1e3:.3f} ms.')
            start_time = perf_counter()
        self.triggers.activate_trigger('maps recalculated', None)
        if self.report_timing:
            self.session.logger.info(f'Running "maps recalculated" trigger for live xmapset #{self.id_string} took {(perf_counter()-start_time)*1e3:.3f} ms.')

    def delete(self):
        print('Deleting {}'.format(self.name))
        self.live_update = False
        self.stop_showing_r_factors()
        self.session.logger.status('', secondary=True)
        super().delete()

    # Callbacks

    def _cover_coords_cb(self, trigger_name, params):
        coords, padding = params
        self.expand_to_cover_coords(coords, padding)

    def _box_changed_cb(self, trigger_name, params):
        center, radius = params
        origin_grid, origin_xyz = _find_box_corner(center, self.cell, self.grid, radius=radius)
        dim = 2*_calculate_grid_padding(radius, self.grid, self.cell)
        self.box_params.set((origin_xyz, origin_grid, dim))
        self.triggers.activate_trigger('map box changed', None)

    def _box_moved_cb(self, trigger_name, center):
        bp = self.box_params
        bp.origin_grid, bp.origin_xyz = _find_box_corner(center, self.cell,
            self.grid, radius=self.display_radius)
        self.triggers.activate_trigger('map box moved', None)

    def start_showing_r_factors(self):
        if not self.live_xmap_mgr:
            self.session.logger.warning('Attempted to start live R-factor display, '
                'but no live crystallographic maps are loaded. Command ignored.')
            return
        if not hasattr(self, '_r_factor_label') or self._r_factor_label is None:
            from chimerax.label import Label
            self._r_factor_label = Label(self.session, self.name+'_r_factors',
                text='', xpos=0.025, ypos=0.025, bold=True, size=30)
            self._r_factor_label_handler = self.triggers.add_handler(
                'maps recalculated', self._update_r_factor_text
            )
        self._update_r_factor_text()

    def _r_factor_string(self, precision=4, trailing=''):
        '''Format the current R-factor(s) for display. A macromolecular manager
        carries a genuine R-free set, so both Rwork and Rfree are shown; a small-
        molecule manager (has_rfree = False) has none - it reports a single R, rather
        than a misleading Rwork == Rfree pair.'''
        lxm = self.live_xmap_mgr
        if lxm is None:
            return ''
        if getattr(lxm, 'has_rfree', True):
            return 'Rwork: {0:0.{p}f}  Rfree: {1:0.{p}f}{t}'.format(
                self.rwork, self.rfree, p=precision, t=trailing)
        return 'R: {0:0.{p}f}{t}'.format(self.rwork, p=precision, t=trailing)

    def _update_r_factor_text(self, *_):
        lb = self._r_factor_label
        lxm = self.live_xmap_mgr
        if not lxm:
            self._r_factor_label_handler = None
            from chimerax.core.triggerset import DEREGISTER
            return DEREGISTER
        lb.text = self._r_factor_string(precision=3, trailing='  ')
        lb.update_drawing()

    def stop_showing_r_factors(self, *_):
        if hasattr(self, '_r_factor_label_handler') and self._r_factor_label_handler is not None:
            self.triggers.remove_handler(self._r_factor_label_handler)
            self._r_factor_label_handler = None
        if hasattr(self, '_r_factor_label') and self._r_factor_label is not None:
            self._r_factor_label.delete()
            self._r_factor_label = None

    @property
    def radiation_type(self):
        '''Scattering regime of this crystal dataset: 'xray' or 'electron'
        (None only if somehow unset). Consumed by child XmapHandler_Live.'''
        return getattr(self, '_radiation', None)

    def take_snapshot(self, session, flags):
        from chimerax.core.models import Model
        data = {
            'crystal manager': self._mgr,
            'model state': Model.take_snapshot(self, session, flags),
            'F/sigF': self._f_sigf_data_name,
            'live update': self.live_update,
            'radiation': getattr(self, '_radiation', 'xray'),
        }
        # Small-molecule crystals carry no ReflectionDataContainer / MTZ (the live maps
        # come from SmallMoleculeXmapMgr, fed by a raw Fobs HKL_data + crystal definition
        # held on self._small_molecule_data). None of that is a child model, so persist it
        # here so a session can rebuild the manager on restore without the source CIF. The
        # expensive symmetry expansion is NOT redone: the maps recompute cheaply by FFT.
        smd = self._small_molecule_data
        if smd is not None:
            fh, fv = smd['fobs'].data
            grid = smd['grid']
            data['small molecule'] = {
                'hall symbol': smd['spacegroup'].symbol_hall,
                'cell dim': smd['cell'].dim,
                'cell angles': smd['cell'].angles_deg,
                'resolution': smd['resolution'],
                'grid': (int(grid.nu), int(grid.nv), int(grid.nw)),
                'fobs hkls': fh,
                'fobs values': fv,
                'radiation': smd.get('radiation', 'xray'),
                'path': smd.get('path'),
            }
        from .. import CLIPPER_STATE_VERSION
        data['version']=CLIPPER_STATE_VERSION
        return data

    @staticmethod
    def restore_snapshot(session, data):
        from chimerax.core.models import Model
        cm = data['crystal manager']
        if cm is None:
            return None
        xmapset = XmapSet(cm, auto_add_to_session=False)
        Model.set_state_from_snapshot(xmapset, session, data['model state'])
        xmapset._f_sigf_data_name = data['F/sigF']
        # v2 sessions lack 'radiation'; default to X-ray so old sessions restore
        # byte-identically. Set before _end_restore_session_cb relaunches the live
        # manager, which reads _radiation to pick the scattering-factor table.
        xmapset._radiation = data.get('radiation', 'xray')
        xmapset._session_restore_live_update = data['live update']
        # Small-molecule crystal data (absent in macromolecular / older sessions). The
        # crystal definition (cell/spacegroup/grid/hklinfo + Fobs) must be reconstructed
        # NOW, before the child XmapHandler_Live models restore: their data-array
        # generation reads self.cell/self.grid (voxel_size), which resolve from
        # _small_molecule_data. The live manager (needs the atomic structure) is launched
        # later in _end_restore_session_cb, once the SymmetryManager has reconnected it.
        sm = data.get('small molecule')
        if sm is not None:
            xmapset._reconstruct_small_molecule_crystal(sm)
        session.triggers.add_handler('end restore session', xmapset._end_restore_session_cb)
        return xmapset

    def _reconstruct_small_molecule_crystal(self, sm):
        '''Rebuild the crystal definition + Fobs (no structure yet) from the persisted
        'small molecule' snapshot block and install it as self._small_molecule_data, so the
        cell/spacegroup/grid/hklinfo accessors work while the child maps restore.'''
        import numpy
        from .. import (Cell, Cell_descr, Spacegroup, Spgr_descr, Resolution,
                        Grid_sampling, HKL_info, HKL_data_F_sigF)
        cell = Cell(Cell_descr(*sm['cell dim'], *sm['cell angles']))
        spacegroup = Spacegroup(Spgr_descr(sm['hall symbol'], Spgr_descr.Hall))
        grid = Grid_sampling(*sm['grid'])
        res = sm['resolution']
        hklinfo = HKL_info(spacegroup, cell, Resolution(res), True)
        fobs = HKL_data_F_sigF(hklinfo)
        fobs.set_data(numpy.asarray(sm['fobs hkls']), numpy.asarray(sm['fobs values']))
        self._radiation = sm.get('radiation', 'xray')
        # structure is filled in _end_restore_session_cb (reconnected by then).
        self._small_molecule_data = {
            'cell': cell, 'spacegroup': spacegroup, 'grid': grid, 'hklinfo': hklinfo,
            'resolution': res, 'fobs': fobs, 'structure': None,
            'path': sm.get('path'), 'radiation': self._radiation}

    def _relaunch_small_molecule_maps(self):
        '''Launch the SmallMoleculeXmapMgr and re-register the restored 2Fo-Fc / Fo-Fc
        handlers so they recompute (cheap FFT, NO symmetry re-expansion). Deferred to
        end-of-restore because it needs the atomic structure, reconnected by the
        SymmetryManager's own end-restore handler (which runs first, parent before child).'''
        smd = self._small_molecule_data
        smd['structure'] = self.structure
        from ..io.small_molecule import register_clipper_atom_attributes
        register_clipper_atom_attributes(self.session)
        self._launch_small_molecule_xmap_mgr(smd)
        for m in self.child_models():
            if isinstance(m, XmapHandler_Live):
                self._live_xmap_mgr.add_xmap(m._map_name, **m._rebuild_args)
                # Reconnect the contour basis the recalc callback rescales against:
                # the difference map uses an absolute level (pin _contour_sigma None so
                # it is not rescaled); the 2Fo-Fc map tracks its winsorized sigma.
                m._contour_sigma = None if m.is_difference_map else m.contour_sigma_basis
                m._session_restore = False
        self.live_update = self._session_restore_live_update

    def _end_restore_session_cb(self, *_):
        if self._small_molecule_data is not None:
            self._relaunch_small_molecule_maps()
        elif self.crystal_data is not None and self._f_sigf_data_name is not None:
            for fsigf in self.all_models():
                if fsigf.name == self._f_sigf_data_name:
                    break
            self._launch_live_xmap_mgr(self.crystal_data, fsigf.data)
            for m in self.child_models():
                if isinstance(m, XmapHandler_Live):
                    self._live_xmap_mgr.add_xmap(m._map_name, **m._rebuild_args)
                    # The restored (absolute) surface levels correspond to the map
                    # as saved; seed the sigma basis so the first recalculation
                    # rescales correctly (restore goes via set_map_state, not
                    # set_xmap_display_style).
                    m._contour_sigma = m.sigma
                    m._session_restore=False
            self.live_update = self._session_restore_live_update
        self.recalc_needed()
        self._mgr.rezone_needed()

        from chimerax.core.triggerset import DEREGISTER
        return DEREGISTER


from .map_handler_base import XmapHandlerBase

class XmapHandler_Static(XmapHandlerBase):
    '''
    An XmapHandler_Static is in effect a resizable window into a periodic
    crystallographic map. The actual map data (a clipper Xmap object) is
    calculated via fast Fourier transform from a pre-calculated set of
    amplitudes and phases (e.g. as provided by a refinement package), and filled
    into the XmapHandler_Static.data array as needed. Mothods are provided for
    tracking and filling a box around the centre of rotation, and static display
    of a given region.
    '''
    #SESSION_SAVE=False
    def __init__(self, mapset, dataset, 
        is_difference_map=False):
        '''
        Args:
            mapset:
                The XmapSet object this belongs to
            name:
                A descriptive name for this map
            f_phi_data:
                The Clipper HKL_Data_F_phi object the map is to be calculated
                from.
            is_difference_map:
                Is this a difference map?
        '''
        name = '(STATIC) '+dataset.name
        self._mapset = mapset
        self._dataset = dataset
        f_phi_data = self._f_phi_data = dataset.data
        from .. import Xmap

        xmap = self._xmap = Xmap(self.spacegroup, self.cell, self.grid)
        xmap.fft_from(f_phi_data)
        super().__init__(mapset, name, is_difference_map=is_difference_map)


    @property
    def xmap(self):
        return self._xmap

    @property
    def stats(self):
        if not hasattr(self, '_stats') or self._stats is None:
            from .. import Map_stats
            all = self._all_stats = Map_stats(self._xmap)
            self._stats = (all.mean, all.std_dev, all.std_dev)
        return self._stats

    def _regrid(self, grid=None):
        '''
        Re-create the real-space map at a new grid sampling (oversampling rate)
        and re-FFT the stored (unchanged) amplitudes/phases into it. The display
        box is refilled separately by the box-change trigger fired after re-grid.
        '''
        from .. import Xmap
        if grid is None:
            grid = self.grid
        xmap = self._xmap = Xmap(self.spacegroup, self.cell, grid)
        xmap.fft_from(self._f_phi_data)
        self._stats = None
        self._all_stats = None

    def is_probably_fcalc_map(self):
        '''
        Guess whether a map loaded from a file is an Fcalc map (calculated
        directly from the model, rather than a 2mFo-DFc / mFo-DFc likelihood map).
        Recognition of the calculated-map column names is centralised in
        io.reflection_classify.
        '''
        from ..io.reflection_classify import map_coeff_info
        return map_coeff_info(self.name).is_fcalc

    def take_snapshot(self, session, flags):
        from chimerax.core.models import Model
        from chimerax.map.session import state_from_map
        data = {
            'model state':  Model.take_snapshot(self, session, flags),
            'volume state': state_from_map(self),
            'is difference map': self._is_difference_map,
            'mapset': self._mapset,
            'F/phi': self._dataset,
        }
        from .. import CLIPPER_STATE_VERSION
        data['version']=CLIPPER_STATE_VERSION
        return data

    @staticmethod
    def restore_snapshot(session, data):
        mapset = data['mapset']
        if mapset is None:
            return None
        try:
            xmh = mapset.add_static_xmap(data['F/phi'],
                is_difference_map=data['is difference map'],
                auto_add_to_session=False, _session_restore=True)
        except AttributeError:
            raise
            return None
        from chimerax.core.models import Model
        from chimerax.map.session import set_map_state
        Model.set_state_from_snapshot(xmh, session, data['model state'])
        set_map_state(data['volume state'], xmh)
        xmh._drawings_need_update()
        return xmh




class XmapHandler_Live(XmapHandlerBase):
    '''
    An XmapHandler_Live is in effect a resizable window into a periodic
    crystallographic map. The actual map data (a clipper Xmap object) is
    recalculated as needed from the combination of atomic coordinates and
    measured diffraction data, and filled into the XmapHandler_Live.data array
    as needed. Mothods are provided for live recalculation, tracking and filling
    a box around the centre of rotation, and static display of a given region.
    '''
    SESSION_SAVE=True

    @property
    def radiation_type(self):
        # Live crystallographic map: report the scattering regime of the owning
        # XmapSet ('xray'/'electron'). Overrides the None default on MapHandlerBase.
        return getattr(self.mapset, 'radiation_type', None)

    def __init__(self, mapset, name,
        is_difference_map=False, session_restore=False):
        '''
        Args:
            mapset:
                The XmapSet object this belongs to
            name:
                A descriptive name for this map
            is_difference_map:
                Is this a difference map?
        '''
        self._map_name = name
        name = '(LIVE) '+name
        super().__init__(mapset, name, is_difference_map=is_difference_map,
            session_restore=session_restore)
        # Whether this map's sharpening B-factor may be changed at runtime.
        # Difference maps are non-adjustable by construction (sharpening a signed
        # residual map has no useful interpretation). add_live_xmap() may override
        # (e.g. ISOLDE marks its hidden MDFF fitting map as non-adjustable).
        self._bsharp_adjustable = not is_difference_map
        # Whether this map is the default target of "clipper bsharp" when the
        # command is applied at model/whole-dataset scope (rather than to one
        # explicitly-named map). The heuristic sharpened/smoothed viewing map is
        # designated; the raw 2mFo-DFc reference map is not.
        self._bsharp_designated = False
        self._mgr_handlers.append(
            (mapset,
            mapset.triggers.add_handler('maps recalculated', self._map_recalc_cb
            ))
        )

    @property
    def xmap_mgr(self):
        return self.mapset.live_xmap_mgr

    @property
    def bsharp_adjustable(self):
        'Whether this map allows runtime sharpening B-factor changes.'
        return getattr(self, '_bsharp_adjustable', not self.is_difference_map)

    @bsharp_adjustable.setter
    def bsharp_adjustable(self, value):
        self._bsharp_adjustable = bool(value)

    @property
    def bsharp_designated(self):
        'Whether this map is the default target of broad-scope "clipper bsharp".'
        return getattr(self, '_bsharp_designated', False)

    @bsharp_designated.setter
    def bsharp_designated(self, value):
        self._bsharp_designated = bool(value)

    @property
    def xmap(self):
        if self.xmap_mgr is None:
            return None
        return self.xmap_mgr.get_xmap_ref(self._map_name)

    @property
    def stats(self):
        all = self.xmap_mgr.get_map_stats(self._map_name)
        return (all.mean, all.std_dev, all.std_dev)

    # Winsorization clip factor (in robust sigmas) for small-molecule contour levels.
    # See contour_sigma_basis.
    SMALL_MOLECULE_WINSORIZE_C = 8.0

    @property
    def _is_small_molecule_map(self):
        from .small_molecule_map import SmallMoleculeXmapMgr
        return isinstance(self.xmap_mgr, SmallMoleculeXmapMgr)

    def _whole_cell_values(self):
        '''The whole periodic unit-cell grid as a flat float64 array, or None. Read
        losslessly over [0, n) in each axis (matching self.sigma, which is the
        whole-cell Clipper std_dev).'''
        xmap = self.xmap
        if xmap is None:
            return None
        from .. import Coord_grid
        gs = xmap.grid_sampling
        return numpy.asarray(xmap.export_section_numpy(
            Coord_grid(0, 0, 0),
            Coord_grid(int(gs.nu), int(gs.nv), int(gs.nw))), numpy.float64).ravel()

    @property
    def robust_sigma(self):
        '''A MAD-based standard-deviation estimate of the whole-cell map, robust to a
        few extreme (heavy-atom) density peaks. Falls back to the raw sigma when the
        grid is unavailable or degenerate.'''
        rho = self._whole_cell_values()
        if rho is None:
            return self.sigma
        med = numpy.median(rho)
        mad = float(numpy.median(numpy.abs(rho - med)) * 1.4826)
        return mad if mad > 0 else self.sigma

    @property
    def contour_sigma_basis(self):
        '''The sigma the default contour levels are pinned to and rescaled by (see
        XmapSet.set_xmap_display_style and _do_recalc_refill).

        For small-molecule maps this is a WINSORIZED sigma, not the raw whole-cell
        sigma. A crystal with heavy atoms produces a handful of enormous density
        peaks - a 53-electron iodine reaches ~200 e/A^3 in 2Fo-Fc versus ~12 for
        carbon - which inflate the raw sigma several-fold; the standard 2.5-sigma
        level then lands above every light-atom peak and the framework contours to
        nothing (COD 2020656 was the reported case). Clipping the map at
        median +/- c*MAD before taking the standard deviation removes the heavy-atom
        tail so the level tracks the light-atom density scale. Macromolecular maps
        are near-Gaussian (no dominant scatterer) and keep the raw sigma unchanged.'''
        if not self._is_small_molecule_map:
            return self.sigma
        rho = self._whole_cell_values()
        if rho is None:
            return self.sigma
        med = numpy.median(rho)
        mad = numpy.median(numpy.abs(rho - med)) * 1.4826
        if not mad > 0:
            return self.sigma
        c = self.SMALL_MOLECULE_WINSORIZE_C
        return float(numpy.clip(rho, med - c * mad, med + c * mad).std())

    @property
    def b_sharp(self):
        '''
        The sharpening (positive) / smoothing (negative) B-factor applied to this
        live map's coefficients before the FFT. Setting a new value recomputes
        just this map from its cached base coefficients (no Fcalc regeneration)
        and refreshes the display immediately, keeping contours fixed in sigma
        units.
        '''
        return getattr(self, '_rebuild_args', {}).get('b_sharp', 0)

    @b_sharp.setter
    def b_sharp(self, value):
        xm = self.xmap_mgr
        if xm is None:
            raise RuntimeError('This map is not backed by a live crystallographic '
                'map manager; its sharpening B-factor cannot be changed.')
        if not hasattr(xm, 'set_map_b_sharp'):
            raise RuntimeError('Dynamic sharpening B-factor adjustment is not '
                'supported for this map type (e.g. small-molecule live maps).')
        if not self.bsharp_adjustable:
            raise RuntimeError('Map "{}" is not adjustable: its sharpening '
                'B-factor is locked (difference map, or a map explicitly marked '
                'non-adjustable such as an MDFF fitting map).'.format(self._map_name))
        value = float(value)
        xm.set_map_b_sharp(self._map_name, value)
        # Keep _rebuild_args in sync so the value survives session save/restore
        # (see XmapSet._end_restore_session_cb, which replays add_xmap(**_rebuild_args)).
        if not hasattr(self, '_rebuild_args'):
            self._rebuild_args = {}
        self._rebuild_args['b_sharp'] = value
        # Refill the display box from the freshly-recomputed map and rescale
        # contours to the new sigma.
        self._map_recalc_cb(self._map_name)

    def _map_recalc_cb(self, name, *_):
        if self.deleted:
            return
        # A hidden display-gated (debug) map is skipped by the recalc loop and left
        # dirty; refilling it would force a synchronous FFT via ensure_current and
        # defeat the gating. It is refreshed on show instead (see
        # XmapSet._debug_map_display_changed_cb).
        if getattr(self, '_display_gated', False) and not self.display:
            return
        # Defer the in-place box refill if a contour worker is still reading the
        # buffer (avoids tearing the surface into garbage triangle indices).
        self._refill_when_idle('recalc', self._do_recalc_refill)

    def _do_recalc_refill(self):
        for s in self.surfaces:
            s._use_thread=True
        self._fill_volume_data(self._data_fill_target, self.box_params.origin_grid)
        # Keep contours fixed in sigma units across recalculation. The absolute
        # surface levels were set against self._contour_sigma; when the model's
        # mean B-factor shifts the map's overall scale (sigma) changes, so rescale
        # the levels by the sigma ratio rather than reusing the stale absolutes.
        old_sigma = getattr(self, '_contour_sigma', None)
        new_sigma = self.contour_sigma_basis
        if old_sigma and new_sigma and old_sigma > 0 and self.surfaces:
            scale = new_sigma / old_sigma
            if scale != 1.0:
                self.set_parameters(surface_levels=[s.level*scale for s in self.surfaces])
        self._contour_sigma = new_sigma
        self.data.values_changed()

    def delete(self):
        print('Deleting {}'.format(self.name))
        self.xmap_mgr.delete_xmap(self._map_name)
        super().delete()

    def take_snapshot(self, session, flags):
        from chimerax.core.models import Model
        from chimerax.map.session import state_from_map
        data = {
            'model state':  Model.take_snapshot(self, session, flags),
            'volume state': state_from_map(self),
            'mapset': self._mapset,
            'map name': self._map_name,
            'kwargs': self._rebuild_args,
            'bsharp_adjustable': self.bsharp_adjustable,
            'bsharp_designated': self.bsharp_designated,
        }
        from .. import CLIPPER_STATE_VERSION
        data['version']=CLIPPER_STATE_VERSION
        return data

    @staticmethod
    def restore_snapshot(session, data):
        mapset = data['mapset']
        xmh = XmapHandler_Live(mapset, data['map name'],
            data['kwargs']['is_difference_map'], session_restore=True)
        xmh._rebuild_args = data['kwargs']
        # Older sessions predate these flags; fall back to the difference-map rule.
        xmh.bsharp_adjustable = data.get('bsharp_adjustable',
            not data['kwargs']['is_difference_map'])
        xmh.bsharp_designated = data.get('bsharp_designated', False)
        #xmh = mapset.add_live_xmap('', **data['kwargs'], auto_add_to_session=False)
        from chimerax.core.models import Model
        from chimerax.map.session import set_map_state
        Model.set_state_from_snapshot(xmh, session, data['model state'])
        set_map_state(data['volume state'], xmh)
        xmh._drawings_need_update()
        return xmh




def map_potential_recommended_bsharp(resolution):
    '''
    Return a recommended sharpening/smoothing B-factor for a given map to
    optimise its use as an MDFF potential. For now this is a simple linear
    function of resolution, passing through zero at 2.5 Angstroms (smoothing
    below, sharpening above). Improved methods will be developed over time.
    '''
    # smooth by 30 A**2 at 1.5A res; sharpen by 30A**2 at 3.5A res; 0 at 2.5A res
    return viewing_recommended_bsharp(resolution, crossover=2.5, low_res_base=35,
        high_res_base=20)

def viewing_recommended_bsharp(resolution, crossover=2.5, low_res_base=45,
        high_res_base=25):
    '''
    For viewing purposes it is also often useful to have a smoothed or
    sharpened visualisation of your map, but the optimal degree of sharpening
    for visualisation is not necessarily the same as that for MDFF.
    '''
    # smooth by 50 A**2 at 1.5A res; sharpen by 50 A**2 at 3.5A res, 0 at 2.5A res
    from math import sqrt
    if resolution < crossover:
        return -high_res_base*sqrt(crossover-resolution) + 2.5
    else:
        return low_res_base*sqrt(resolution-crossover) - 2.5



def _select_calc_datasets(datasets, map_columns):
    '''
    Decide which calculated (F/phi) datasets to open as static maps.

    If `map_columns` is None, all datasets are selected (the historical default;
    the caller then hides probable Fcalc maps). Otherwise `map_columns` is a list
    of user-supplied strings, and a dataset is selected when any of them matches
    (case-insensitively, EXACTLY — not as a substring) the dataset's full name,
    one of its column labels, or its map type. Exact matching is essential
    because e.g. "FOFCWT" is a substring of "2FOFCWT": substring matching on
    crystallographic labels would make the difference-map token also select the
    2mFo-DFc map. So "FOFCWT" selects only the mFo-DFc map, "2FOFCWT" only the
    2mFo-DFc map, and "mFo-DFc" selects every difference map by type. The MTZ
    browser passes full dataset names, which match on the first target.
    '''
    if map_columns is None:
        return list(datasets)
    from ..io.reflection_classify import extract_column_labels, map_coeff_info
    tokens = set(t.strip().lower() for t in map_columns if t.strip())
    selected = []
    for dataset in datasets:
        targets = set(l.lower() for l in extract_column_labels(dataset.name))
        targets.add(dataset.name.lower())
        targets.add(map_coeff_info(dataset.name).map_type.lower())
        if tokens & targets:
            selected.append(dataset)
    return selected


def _calculate_grid_padding(radius, grid, cell):
    '''
    Calculate the number of grid steps needed on each crystallographic axis
    in order to capture at least radius angstroms in x, y and z.
    '''
    corner_mask = numpy.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,0,0],[1,1,1]])
    corners = (corner_mask * radius).astype(numpy.float32)
    grid_upper = numpy.zeros([8,3], int)
    grid_lower = numpy.zeros([8,3], int)
    from .. import Coord_orth
    for i, c in enumerate(corners):
        co = Coord_orth(c)
        cm = co.coord_frac(cell).coord_map(grid).uvw
        grid_upper[i,:] = numpy.ceil(cm).astype(int)
        grid_lower[i,:] = numpy.floor(cm).astype(int)
    return grid_upper.max(axis=0) - grid_lower.min(axis=0)


def _find_box_corner(center, cell, grid, radius = 20):
    '''
    Find the bottom corner (i.e. the origin) of a rhombohedral box
    big enough to hold a sphere of the desired radius.
    '''
    from .. import Coord_frac, Coord_orth, Coord_grid
    radii_frac = Coord_frac(radius/cell.dim)
    center_frac = Coord_orth(center).coord_frac(cell)
    bottom_corner_grid = center_frac.coord_grid(grid) \
                - Coord_grid(_calculate_grid_padding(radius, grid, cell))
    bottom_corner_orth = bottom_corner_grid.coord_frac(grid).coord_orth(cell)
    return bottom_corner_grid.uvw, bottom_corner_orth.xyz

def _get_bounding_box(coords, grid, cell, padding=2):
    '''
    Find the minimum and maximum grid coordinates of a box which will
    encompass the given (x,y,z) coordinates plus padding (in Angstroms).
    '''
    from .. import Util, Coord_grid
    grid_pad = _calculate_grid_padding(padding, grid, cell)
    box_bounds_grid = Util.get_minmax_grid(coords, cell, grid)\
                        + numpy.array((-grid_pad, grid_pad))
    box_origin_grid = box_bounds_grid[0]
    box_origin_xyz = Coord_grid(box_origin_grid).coord_frac(grid).coord_orth(cell)
    dim = box_bounds_grid[1] - box_bounds_grid[0]
    return [box_origin_grid, box_origin_xyz, dim]
